name: Deploy eNanayCare

on:
  push:
    branches:
      - main  # change to "master" if that's your branch
      
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # or 20 if your Ionic supports it

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      # 🚀 If using GitHub Pages:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
